remote_theme:  architect@v0.2.0
plugins:
- jekyll-remote-theme 

gem "github-pages", group: :jekyll_plugins

title: Fruit Recognizer
description: An Image Classification API that categorizes 20 different types of fruits found around the world.

author:
  name: Sadik Al Jarif
